namespace Doctally.Api.DTOs;

public record CriarPacienteRequest(
    // 1. Identificação pessoal
    string NomeCompleto,
    DateOnly DataNascimento,
    string? Sexo,
    string? NomeMae,
    string? EstadoCivil,
    string? NaturalidadeMunicipio,
    string? NaturalidadeUf,
    string? Nacionalidade,
    string? Profissao,
    string? GrauInstrucao,
    // 2. Documentação
    string Cpf,
    string? Rg,
    string? RgOrgaoEmissor,
    string? Cns,
    string? Convenio,
    string? NumeroCarteirinha,
    DateOnly? ValidadeConvenio,
    // 3. Contatos
    string? Telefone,
    string? TelefoneFixo,
    string? Email,
    string? ComoConheceuClinica,
    // 4. Endereço residencial
    string? Cep,
    string? Logradouro,
    string? EnderecoNumero,
    string? Complemento,
    string? Bairro,
    string? Municipio,
    string? Uf,
    string? PontoReferencia,
    // 5. Contato de emergência
    string? EmergenciaNome,
    string? EmergenciaParentesco,
    string? EmergenciaTelefone,
    // 6. Responsável (menor de idade/incapaz)
    string? ResponsavelNome,
    string? ResponsavelCpf,
    string? ResponsavelRg,
    string? ResponsavelParentesco,
    string? ResponsavelTelefone,
    // 7. Informações de saúde / anamnese básica
    bool PossuiAlergias,
    string? AlergiasQuais,
    bool UsaMedicacaoContinua,
    string? MedicacaoQuais,
    string? StatusTabagismo,
    string? TabagismoDetalhe,
    bool PossuiDoencaCronica,
    string? DoencaCronicaQuais,
    string? CirurgiasInternacoes,
    // 8. Consentimento LGPD
    bool ConsentimentoLgpd
);

public record PacienteResponse(
    Guid Id,
    string NomeCompleto,
    DateOnly DataNascimento,
    string? Sexo,
    string? NomeMae,
    string? EstadoCivil,
    string? NaturalidadeMunicipio,
    string? NaturalidadeUf,
    string? Nacionalidade,
    string? Profissao,
    string? GrauInstrucao,
    string Cpf,
    string? Rg,
    string? RgOrgaoEmissor,
    string? Cns,
    string? Convenio,
    string? NumeroCarteirinha,
    DateOnly? ValidadeConvenio,
    string? Telefone,
    string? TelefoneFixo,
    string? Email,
    string? ComoConheceuClinica,
    string? Cep,
    string? Logradouro,
    string? EnderecoNumero,
    string? Complemento,
    string? Bairro,
    string? Municipio,
    string? Uf,
    string? PontoReferencia,
    string? EmergenciaNome,
    string? EmergenciaParentesco,
    string? EmergenciaTelefone,
    string? ResponsavelNome,
    string? ResponsavelCpf,
    string? ResponsavelRg,
    string? ResponsavelParentesco,
    string? ResponsavelTelefone,
    bool PossuiAlergias,
    string? AlergiasQuais,
    bool UsaMedicacaoContinua,
    string? MedicacaoQuais,
    string? StatusTabagismo,
    string? TabagismoDetalhe,
    bool PossuiDoencaCronica,
    string? DoencaCronicaQuais,
    string? CirurgiasInternacoes,
    bool ConsentimentoLgpd
);
